### ISSUE TITLE
missing support for boron atoms

### ISSUE THREAD

**Issue by chstem** [jensengroup/xyz2mol#17]
For any compound containing boron atoms the code fails with the following traceback:

```
Traceback (most recent call last):
  File "test.py", line 201, in <module>
    test_smiles_from_adjacent_matrix(smiles)
  File "test.py", line 108, in test_smiles_from_adjacent_matrix
    new_mol = x2m.AC2mol(new_mol, adjacent_matrix, atoms, charge, charged_fragments, quick)
  File "~/xyz2mol/xyz2mol.py", line 481, in AC2mol
    allow_charged_fragments=allow_charged_fragments)
  File "~/xyz2mol/xyz2mol.py", line 307, in BO2mol
    mol_charge)
  File "~/xyz2mol/xyz2mol.py", line 321, in set_atomic_charges
    charge = get_atomic_charge(atom, atomic_valence_electrons[atom], BO_valences[i])
KeyError: 5

```

This can be easily reproduced by adding `'B'` to `__TEST_SMILES__` in `test.py`.

**Comment by jhjensen2** [comment]
I have now added support for boron.
