### ISSUE TITLE
'charge_OK' referenced before assignment

### ISSUE THREAD

**Issue by peterbjorgensen** [jensengroup/xyz2mol#19]
With this molecule from the QM9 dataset, the code crashes.
```
14
gdb 17732	4.70059	2.58463	2.12795	1.0519	59.76	-0.2373	0.0592	0.2964	645.2599	0.108401	-382.406252	-382.40113	-382.400186	-382.435117	21.702	
C	-0.0014375802	 1.4421265986	-0.0783539803	-0.173276
O	 1.4279653634	 1.680945134	-0.0080214605	-0.29881
C	 2.039377242	 0.3725618284	 0.2411593666	 0.062175
C	 1.2851358508	-0.6213188634	-0.6464578571	-0.111225
C	 0.8430229634	-1.6066653822	 0.4586764181	-0.013319
O	-0.6285080863	-1.2983195241	 0.3001821354	-0.387437
C	 0.0746804748	-0.0497085445	 0.1590760325	 0.408626
C	 1.1413118459	-0.3240770307	 1.2671705337	-0.111221
H	-0.5189406562	 2.0037218427	 0.7059437231	 0.118485
H	-0.386047951	 1.7290984788	-1.0622458982	 0.118485
H	 3.1161899719	 0.5067876894	 0.3012405973	 0.091326
H	 1.3044717917	-0.7751572283	-1.7230279892	 0.095211
H	 1.0880849399	-2.6505456812	 0.6392374907	 0.105768
H	 0.99978614	-0.1454833675	 2.3307110179	 0.095211
```
Here is the stack trace:
```
python /home/peter/kodesjov/xyz2mol/xyz2mol.py dsgdb9nsd_017732.xyz 
Traceback (most recent call last):
  File "/home/peter/kodesjov/xyz2mol/xyz2mol.py", line 789, in <module>
    mol = xyz2mol(atoms, xyz_coordinates,
  File "/home/peter/kodesjov/xyz2mol/xyz2mol.py", line 710, in xyz2mol
    new_mol = AC2mol(mol, AC, atoms, charge,
  File "/home/peter/kodesjov/xyz2mol/xyz2mol.py", line 478, in AC2mol
    BO, atomic_valence_electrons = AC2BO(
  File "/home/peter/kodesjov/xyz2mol/xyz2mol.py", line 468, in AC2BO
    if not charge_OK:
UnboundLocalError: local variable 'charge_OK' referenced before assignment
```

**Comment by jhjensen2** [comment]
The problem is that the distance criterion identifies extra bonds to 2 carbons. I have now added an error message if this happens. The problem can be fixed for this molecule by the --use-huckel keyword.
